basePath: /api/
definitions:
  domain.User:
    properties:
      id:
        type: integer
      login:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: integer
      surname:
        type: string
    type: object
host: localhost:8181
info:
  contact:
    email: rovshan27121@gmail.com
    name: Rovshan Gasanov
  description: Swagger API for Golang GoTest.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: GoTest Swagger API
  version: "1.0"
paths:
  /users:
    get:
      operationId: "2"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
      summary: GetUsers
  /users/{user_id}:
    get:
      operationId: "1"
      parameters:
      - description: UserID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      summary: GetUser
swagger: "2.0"
